#!/bin/bash

SCRIPTDIR=`dirname "$BASH_SOURCE"`

NODE_DIR="${SCRIPTDIR}/state-node-shelly-testnet"
mkdir -p ${NODE_DIR}

choice() { i=$1; shift; eval "echo \${$((i + 1))}"; }


echo ${SCRIPTDIR}

BASE_CONFG="${SCRIPTDIR}/../src/tconfig/mainnet_candidate-config.json"
TOPOLOGY_CONFIG="${SCRIPTDIR}/../src/tconfig/mainnet_candidate-topology.json"


CARDANO_NODE="/home/nsaha/.local/bin/cardano-node"
HOST_IP="$(wget http://ipecho.net/plain -O - -q ; echo)"
PORT=3001
DB_DIR="${NODE_DIR}/db-ff"
SOCKET="${NODE_DIR}/node.socket"


COMMAND= ${CARDANO_NODE} run \
       --config ${BASE_CONFG} \
       --database-path ${DB_DIR} \
       --topology ${TOPOLOGY_CONFIG} \
       --socket-path ${SOCKET} \
       --host-addr ${HOST_IP} \
       --port ${PORT}

echo "Starting cardano-node run: ${COMMAND}"
exec ${COMMAND}

export CARDANO_NODE_SOCKET_PATH=$PWD/${SOCKET}
