# Run this workflow every time a new commit pushed to your repository
on: push


jobs:
  build:
    name: Build the cardano binaries
    runs-on: ubuntu-latest
    
    steps:
      - name: Build the tagged Docker image
        run: |          
          docker build --build-arg CARDANO_NODE_VERSION=${{ secrets.CARDANO_NODE_VERSION }} \
          --build-arg CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }} .
        with:
          context: .
          file: ./Dockerfile
