# Run this workflow every time a new commit pushed to your repository
on: [workflow_dispatch]

jobs:
  cardano-build:
    name: Build the cardano binaries
    runs-on: ubuntu-latest    
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:"
          echo ${{ secrets.CLOUDSMITH_API_KEY }}
          echo ${{ secrets.CARDANO_NODE_VERSION }}
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: ./
        env:
          CARDANO_NODE_VERSION: ${{ secrets.CARDANO_NODE_VERSION }}
          CLOUDSMITH_API_KEY:  ${{ secrets.CLOUDSMITH_API_KEY }}
