# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  cardano-build:
    name: Build the cardano binaries
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: ./
        id: cardano-node-build
        env:
          CARDANO_NODE_VERSION: ${{ secrets.dev.CARDANO_NODE_VERSION }}
          CLOUDSMITH_API_KEY:  ${{ secrets.dev.CLOUDSMITH_API_KEY }}
