# Run this workflow every time a new commit pushed to your repository
on: [workflow_dispatch]

jobs:
  cardano-build:
    name: Build the cardano binaries
    runs-on: ubuntu-latest    
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action CLOUDSMITH_API_KEY Secret will be masked:"
          echo ${{ secrets.CLOUDSMITH_API_KEY }}
          echo "Trick to echo GitHub Actions Secret:"
          echo ${{secrets.CLOUDSMITH_API_KEY}} | sed 's/./& /g'
          echo "Now the version of cardano node"
          echo ${{ secrets.CARDANO_NODE_VERSION }}
          echo "Now the version of cardano node unmasked"
          echo ${{ secrets.CARDANO_NODE_VERSION }}| sed 's/./& /g'          

      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --build-arg CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }} --build-arg CARDANO_NODE_VERSION=${{ secrets.CARDANO_NODE_VERSION }} .
        
   #   - name: Build Docker image
   #     uses: ./
   #     env:
   #       CARDANO_NODE_VERSION: ${{ secrets.CARDANO_NODE_VERSION }}
   #       CLOUDSMITH_API_KEY:  ${{ secrets.CLOUDSMITH_API_KEY }}
