# Run this workflow every time a new commit pushed to your repository
on: [workflow_dispatch]

jobs:
  cardano-db-sync-build:
    name: Build the cardano-db-sync  binaries
    runs-on: ubuntu-latest    
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "Now the version of cardano-db-sync"
          echo ${{ secrets.CARDANO_DB_SYNC_VERSION }}
          echo "Now the version of cardano node unmasked"
          echo ${{ secrets.CARDANO_DB_SYNC_VERSION }}| sed 's/./& /g'          

      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --build-arg CARDANO_DB_SYNC_VERSION=${{ secrets.CARDANO_DB_SYNC_VERSION }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --file ./Dockerfile.DbSync
        
   #   - name: Build Docker image
   #     uses: ./
   #     env:
   #       CARDANO_NODE_VERSION: ${{ secrets.CARDANO_NODE_VERSION }}
   #       CLOUDSMITH_API_KEY:  ${{ secrets.CLOUDSMITH_API_KEY }}
