# Run this workflow every time a new commit pushed to your repository
on: [workflow_dispatch]

jobs:
  cardano-build:
    name: Build the cardano binaries
    runs-on: ubuntu-latest    
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "Now the version of cardano node"
          echo ${{ secrets.CARDANO_NODE_VERSION }}
          echo "Now the version of cardano node unmasked"
          echo ${{ secrets.CARDANO_NODE_VERSION }}| sed 's/./& /g'          

      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --build-arg CARDANO_NODE_VERSION=${{ secrets.CARDANO_NODE_VERSION }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} .
        
   #   - name: Build Docker image
   #     uses: ./
   #     env:
   #       CARDANO_NODE_VERSION: ${{ secrets.CARDANO_NODE_VERSION }}
   #       CLOUDSMITH_API_KEY:  ${{ secrets.CLOUDSMITH_API_KEY }}
